name: Verify patches

on:
  schedule:
    - cron:  '0 14 * * *'
  workflow_dispatch:
  push:

jobs:
  verify:
    name: Verify patches
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
    - name: Install depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$PWD/depot_tools" >> $GITHUB_PATH
    - name: Checkout PDFium
      timeout-minutes: 15
      run: |
        gclient config --unmanaged "https://pdfium.googlesource.com/pdfium.git"
        gclient sync --no-history --shallow
    - name: Create patch script
      run: |
        cat >patch.sh <<END
        set -eux
        git -C pdfium reset --hard
        gclient sync -R
        PDFium_TARGET_OS=\$1 steps/03-patch.sh
        END
        chmod +x patch.sh
    - name: Apply patches for Android
      run: ./patch.sh android
      if: always()
    - name: Apply patches for iOS
      run: ./patch.sh ios
      if: always()
    - name: Apply patches for Linux
      run: ./patch.sh linux
      if: always()
    - name: Apply patches for macOS
      run: ./patch.sh mac
      if: always()
    - name: Apply patches for WASM
      run: ./patch.sh wasm
      if: always()
    - name: Apply patches for Windows
      run: ./patch.sh win
      if: always()